version: '3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - 8883:8883
      - 1883:1883
    environment:
      - MQTT_USERNAME=amr
      - MQTT_PASSWORD=amr
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-conf:
  mosquitto-data:
  mosquitto-log:
